### ISSUE TITLE
Zowe z/OS runtime check needs to allow z/OS V3.1 environment 

### ISSUE THREAD

**Issue by armstro** [zowe/zowe-common-c#372]
**Describe the bug**
error: z/OS version = 0x01030100, max supported version = 0x01020500 - CAA fields require verification  shows up in the zssServer logs.  And appServer blows up because the zss server is down

Now that there is a Preview of z/OS V3.1 https://www.ibm.com/common/ssi/ShowDoc.wss?docURL=/common/ssi/rep_ca/3/897/ENUS223-013/index.html Zowe needs to allow this as a runtime environment. z/OS beta customers and developers will want to test Zowe on z/OS V3.1 leading up to z/OS V3.1 GA in the fall. 

Logic is located here: 
https://github.com/zowe/zowe-common-c/blob/staging/c/le.c#L113-L127 

**Steps to Reproduce**

1.
2.

**Expected behavior**

**Screenshots (if needed)**

**Logs**

**Describe your environment**

- Zowe version number (Check the Desktop login screen, or manifest.json in the Zowe install folder): 
- Install method (pax, smpe, kubernetes, github clone):
- Operating system (z/OS, kubernetes, etc) and OS version:
- Node.js version number (Shown in logs, or via `node --version`):
- Java version number (Shown in logs, or via `java -version`):
- z/OSMF version:
- What is the output of log message ZWES1014I:
- Environment variables in use:

**Additional context**

**Comment by 1000TurquoisePogs** [comment]
The code in question effects zss, configmgr, and launcher.
There are builds that simply change the number https://github.com/zowe/zowe-common-c/pull/376 to allow these parts of zowe to run on z/os 3.1, but do not guarantee they work well, as such testing is ongoing.
Making builds of multiple components requires use of the build system of github.com/zowe/zowe-install-packaging so I'd recommend people wanting to use zowe on 3.1 to wait until such PRs are merged (soon) or contact the zowe community on slack about getting such a build.

Going foward, we're looking to change the "error" message to an item that can be configured to be a "warning" instead, by consent of users, so that on a future z/os, people can get ahead of zowe testing if desired.
That change too is coming soon.

**Comment by armstro** [comment]
Can we close this issue?

**Comment by 1000TurquoisePogs** [comment]
Implemented.

**Comment by armstro** [comment]
Quick question - is there a section on the Zowe doc where the use of this test and the bypass is described? I can't recall if the default is to not allow startup but then a config file needs to acknowledge bypass.
